### ISSUE TITLE
Decide on how output directories should be created/handled

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#188] opened 2021-09-02 19:10 UTC
I'm not sure if this is the reason I'm seeing weird behavior when trying to resume an interrupted job, but regardless, this is making it difficult to track down files. I am navigating to `params.outdir` expecting to see the generated files but instead have to navigate two more sub-directories. The `workflow.sessionId` is also not obvious to an end user, as this does not appear to be a user-defined input.

Could we keep `params.out` and discard `params.interim_dir`? Then for each metagenome provided, a sub-directory in `params.out` containing all of the metagenome's respective files could be created. This would make looking up a particular genome much easier.

_Originally posted by @WiscEvan in https://github.com/KwanLab/Autometa/pull/157#r697005698_

**Comment by WiscEvan** [comment] 2021-11-11 19:53
This looks like a duplicate of #160 --> I'll link to this in that issue so we can consolidate these

**Closed by WiscEvan** 2021-11-11 19:53 UTC
Labels: enhancement, nextflow
